"""список покупок

Revision ID: 2d2b1acecad5
Revises: bb6017c17e64
Create Date: 2024-10-10 22:32:44.888222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2b1acecad5'
down_revision: Union[str, None] = 'bb6017c17e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_list',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('array_user_name', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('items', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('users', sa.Column('array_shop_list', sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'array_shop_list')
    op.drop_table('shop_list')
    # ### end Alembic commands ###
