"""user_id

Revision ID: 5feca57a720b
Revises: 963e27abe849
Create Date: 2024-10-17 23:35:05.216648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5feca57a720b'
down_revision: Union[str, None] = '963e27abe849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_all', 'username')
    op.add_column('users', sa.Column('user_name', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_name')
    op.add_column('training_all', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
