"""fix tables

Revision ID: 66201807ad34
Revises: aa1b6ec91e7c
Create Date: 2024-09-28 11:09:25.884490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66201807ad34'
down_revision: Union[str, None] = 'aa1b6ec91e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_exer_train2', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('name_exer_train3', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('name_exer_train4', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('name_exer_train5', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name_exer_train5')
    op.drop_column('users', 'name_exer_train4')
    op.drop_column('users', 'name_exer_train3')
    op.drop_column('users', 'name_exer_train2')
    # ### end Alembic commands ###
