"""fix

Revision ID: 6a4b0354b40c
Revises: df0632cba870
Create Date: 2024-08-18 23:13:57.538281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4b0354b40c'
down_revision: Union[str, None] = 'df0632cba870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('leg_uid', sa.Uuid(), nullable=True),
    sa.Column('beak_uid', sa.Uuid(), nullable=True),
    sa.Column('breast_uid', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name_training', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['beak_uid'], ['beak.uid'], ),
    sa.ForeignKeyConstraint(['breast_uid'], ['breast.uid'], ),
    sa.ForeignKeyConstraint(['leg_uid'], ['leg.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('workout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('leg_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('beak_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('breast_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('name_training', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['beak_uid'], ['beak.uid'], name='workout_beak_uid_fkey'),
    sa.ForeignKeyConstraint(['breast_uid'], ['breast.uid'], name='workout_breast_uid_fkey'),
    sa.ForeignKeyConstraint(['leg_uid'], ['leg.uid'], name='workout_leg_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='workout_pkey')
    )
    op.drop_table('training')
    # ### end Alembic commands ###
