"""default shop list

Revision ID: 83ec7dcededd
Revises: ea3cdc91c736
Create Date: 2024-11-30 18:21:27.449545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ec7dcededd'
down_revision: Union[str, None] = 'ea3cdc91c736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_shop_list', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_shop_list')
    # ### end Alembic commands ###
