"""user_id

Revision ID: 963e27abe849
Revises: dd3d8ef13659
Create Date: 2024-10-17 23:21:40.700105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '963e27abe849'
down_revision: Union[str, None] = 'dd3d8ef13659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_list', sa.Column('array_user_id', sa.ARRAY(sa.Text()), nullable=True))
    op.drop_column('shop_list', 'array_username')
    op.add_column('training_all', sa.Column('user_id', sa.Text(), nullable=True))
    op.drop_column('training_all', 'user_name')
    op.add_column('users', sa.Column('user_id', sa.Text(), nullable=True))
    op.drop_constraint('users_user_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_name_key', 'users', ['user_name'])
    op.drop_column('users', 'user_id')
    op.add_column('training_all', sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('training_all', 'user_id')
    op.add_column('shop_list', sa.Column('array_username', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.drop_column('shop_list', 'array_user_id')
    # ### end Alembic commands ###
