"""change tables

Revision ID: 98f3edc0102a
Revises: 
Create Date: 2024-08-18 19:34:16.080534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f3edc0102a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beak',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('triceps_bench_press', sa.Float(), nullable=True),
    sa.Column('french_bench_press', sa.Float(), nullable=True),
    sa.Column('kettlebell', sa.Float(), nullable=True),
    sa.Column('gravitron', sa.Float(), nullable=True),
    sa.Column('upper_block', sa.Float(), nullable=True),
    sa.Column('lower_block', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('breast',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bench_press', sa.Float(), nullable=True),
    sa.Column('bench_press_inclined', sa.Float(), nullable=True),
    sa.Column('pullover', sa.Float(), nullable=True),
    sa.Column('dumbbells', sa.Float(), nullable=True),
    sa.Column('block', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('leg',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('army_bench_press', sa.Float(), nullable=True),
    sa.Column('craving_for_chin', sa.Float(), nullable=True),
    sa.Column('head_press', sa.Float(), nullable=True),
    sa.Column('knee_bend', sa.Float(), nullable=True),
    sa.Column('platform_press', sa.Float(), nullable=True),
    sa.Column('extension_of_block', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('workout',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('leg_uid', sa.Uuid(), nullable=True),
    sa.Column('beak_uid', sa.Uuid(), nullable=True),
    sa.Column('breast_uid', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['beak_uid'], ['beak.uid'], ),
    sa.ForeignKeyConstraint(['breast_uid'], ['breast.uid'], ),
    sa.ForeignKeyConstraint(['leg_uid'], ['leg.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    op.drop_table('leg')
    op.drop_table('breast')
    op.drop_table('beak')
    # ### end Alembic commands ###
