"""add users

Revision ID: aa1b6ec91e7c
Revises: e2b302d2c2dc
Create Date: 2024-09-21 16:50:01.675051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1b6ec91e7c'
down_revision: Union[str, None] = 'e2b302d2c2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('last_date_license', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_access', sa.Boolean(), nullable=True),
    sa.Column('name_trainings', sa.Text(), nullable=True),
    sa.Column('name_exer_train1', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.add_column('training_all', sa.Column('user_name', sa.Text(), nullable=False))
    op.drop_column('training_all', 'name_training')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_all', sa.Column('name_training', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('training_all', 'user_name')
    op.drop_table('users')
    # ### end Alembic commands ###
