"""homeassistant

Revision ID: b4c5a7512cfb
Revises: f194ca0180e8
Create Date: 2025-02-04 22:01:18.512347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c5a7512cfb'
down_revision: Union[str, None] = 'f194ca0180e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_activity',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('movement_status_1', sa.Boolean(), nullable=False),
    sa.Column('movement_status_2', sa.Boolean(), nullable=False),
    sa.Column('movement_status_3', sa.Boolean(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_activity')
    # ### end Alembic commands ###
