"""fix tables

Revision ID: b72789fef4bf
Revises: 18dea3339571
Create Date: 2024-09-29 22:55:12.234225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72789fef4bf'
down_revision: Union[str, None] = '18dea3339571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_all', sa.Column('index_train', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_all', 'index_train')
    # ### end Alembic commands ###
