"""удалил старые таблицы

Revision ID: bb6017c17e64
Revises: b72789fef4bf
Create Date: 2024-10-09 23:03:18.623264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6017c17e64'
down_revision: Union[str, None] = 'b72789fef4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    op.drop_table('beak')
    op.drop_table('breast')
    op.drop_table('leg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leg',
    sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('army_bench_press', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('craving_for_chin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('head_press', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('knee_bend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('platform_press', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extension_of_block', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='leg_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('breast',
    sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('bench_press', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bench_press_inclined', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pullover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dumbbells', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('block', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='breast_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('beak',
    sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('triceps_bench_press', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('french_bench_press', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('kettlebell', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gravitron', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_block', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lower_block', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='beak_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('training',
    sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('leg_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('beak_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('breast_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('name_training', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beak_uid'], ['beak.uid'], name='training_beak_uid_fkey'),
    sa.ForeignKeyConstraint(['breast_uid'], ['breast.uid'], name='training_breast_uid_fkey'),
    sa.ForeignKeyConstraint(['leg_uid'], ['leg.uid'], name='training_leg_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='training_pkey')
    )
    # ### end Alembic commands ###
