"""default shop list

Revision ID: c2aaa80991cb
Revises: 83ec7dcededd
Create Date: 2024-11-30 18:22:01.175752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2aaa80991cb'
down_revision: Union[str, None] = '83ec7dcededd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_shop_list_uid', sa.UUID(), nullable=True))
    op.drop_column('users', 'default_shop_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_shop_list', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('users', 'default_shop_list_uid')
    # ### end Alembic commands ###
