"""new home

Revision ID: cfc2473a48ac
Revises: b4c5a7512cfb
Create Date: 2025-03-01 21:12:04.267832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc2473a48ac'
down_revision: Union[str, None] = 'b4c5a7512cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_activity', sa.Column('movement_status_4', sa.Boolean(), nullable=False))
    op.add_column('home_activity', sa.Column('movement_status_5', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_activity', 'movement_status_5')
    op.drop_column('home_activity', 'movement_status_4')
    # ### end Alembic commands ###
