"""fix

Revision ID: dd3d8ef13659
Revises: 2d2b1acecad5
Create Date: 2024-10-12 12:12:31.498143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd3d8ef13659'
down_revision: Union[str, None] = '2d2b1acecad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_list', sa.Column('array_username', sa.ARRAY(sa.Text()), nullable=False))
    op.drop_column('shop_list', 'array_user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_list', sa.Column('array_user_name', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.drop_column('shop_list', 'array_username')
    # ### end Alembic commands ###
