"""new exer

Revision ID: e2b302d2c2dc
Revises: 46b68478c3d1
Create Date: 2024-09-21 16:19:40.020838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b302d2c2dc'
down_revision: Union[str, None] = '46b68478c3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train1',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ex1', sa.Float(), nullable=True),
    sa.Column('ex2', sa.Float(), nullable=True),
    sa.Column('ex3', sa.Float(), nullable=True),
    sa.Column('ex4', sa.Float(), nullable=True),
    sa.Column('ex5', sa.Float(), nullable=True),
    sa.Column('ex6', sa.Float(), nullable=True),
    sa.Column('ex7', sa.Float(), nullable=True),
    sa.Column('ex8', sa.Float(), nullable=True),
    sa.Column('ex9', sa.Float(), nullable=True),
    sa.Column('ex10', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('train2',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ex1', sa.Float(), nullable=True),
    sa.Column('ex2', sa.Float(), nullable=True),
    sa.Column('ex3', sa.Float(), nullable=True),
    sa.Column('ex4', sa.Float(), nullable=True),
    sa.Column('ex5', sa.Float(), nullable=True),
    sa.Column('ex6', sa.Float(), nullable=True),
    sa.Column('ex7', sa.Float(), nullable=True),
    sa.Column('ex8', sa.Float(), nullable=True),
    sa.Column('ex9', sa.Float(), nullable=True),
    sa.Column('ex10', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('train3',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ex1', sa.Float(), nullable=True),
    sa.Column('ex2', sa.Float(), nullable=True),
    sa.Column('ex3', sa.Float(), nullable=True),
    sa.Column('ex4', sa.Float(), nullable=True),
    sa.Column('ex5', sa.Float(), nullable=True),
    sa.Column('ex6', sa.Float(), nullable=True),
    sa.Column('ex7', sa.Float(), nullable=True),
    sa.Column('ex8', sa.Float(), nullable=True),
    sa.Column('ex9', sa.Float(), nullable=True),
    sa.Column('ex10', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('train4',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ex1', sa.Float(), nullable=True),
    sa.Column('ex2', sa.Float(), nullable=True),
    sa.Column('ex3', sa.Float(), nullable=True),
    sa.Column('ex4', sa.Float(), nullable=True),
    sa.Column('ex5', sa.Float(), nullable=True),
    sa.Column('ex6', sa.Float(), nullable=True),
    sa.Column('ex7', sa.Float(), nullable=True),
    sa.Column('ex8', sa.Float(), nullable=True),
    sa.Column('ex9', sa.Float(), nullable=True),
    sa.Column('ex10', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('train5',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ex1', sa.Float(), nullable=True),
    sa.Column('ex2', sa.Float(), nullable=True),
    sa.Column('ex3', sa.Float(), nullable=True),
    sa.Column('ex4', sa.Float(), nullable=True),
    sa.Column('ex5', sa.Float(), nullable=True),
    sa.Column('ex6', sa.Float(), nullable=True),
    sa.Column('ex7', sa.Float(), nullable=True),
    sa.Column('ex8', sa.Float(), nullable=True),
    sa.Column('ex9', sa.Float(), nullable=True),
    sa.Column('ex10', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('training_all',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('train1_uid', sa.Uuid(), nullable=True),
    sa.Column('train2_uid', sa.Uuid(), nullable=True),
    sa.Column('train3_uid', sa.Uuid(), nullable=True),
    sa.Column('train4_uid', sa.Uuid(), nullable=True),
    sa.Column('train5_uid', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name_training', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train1_uid'], ['train1.uid'], ),
    sa.ForeignKeyConstraint(['train2_uid'], ['train2.uid'], ),
    sa.ForeignKeyConstraint(['train3_uid'], ['train3.uid'], ),
    sa.ForeignKeyConstraint(['train4_uid'], ['train4.uid'], ),
    sa.ForeignKeyConstraint(['train5_uid'], ['train5.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_all')
    op.drop_table('train5')
    op.drop_table('train4')
    op.drop_table('train3')
    op.drop_table('train2')
    op.drop_table('train1')
    # ### end Alembic commands ###
