"""verif_code

Revision ID: ea3cdc91c736
Revises: ac0c6019d480
Create Date: 2024-11-28 21:35:41.228513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3cdc91c736'
down_revision: Union[str, None] = 'ac0c6019d480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vefiry_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vefiry_code')
    # ### end Alembic commands ###
