name: Deploy

on:
  pull_request:
    types:
      - closed
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/projects/web_server && git pull origin master && docker build -t web_server:latest . && docker compose -f /home/${{ secrets.SSH_USER }}/projects/compose/telegram.yaml down && docker compose -f /home/${{ secrets.SSH_USER }}/projects/compose/telegram.yaml up"
          echo "Deployment completed."
      - name: cleanup keys
        if: always()
        run: rm -rf ~/.ssh